### ISSUE TITLE
SQL² ⇒ LP: Missing `ShiftMap` on `FROM`

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1298]
`FROM \test\zips` should be represented by the LP `ShiftMap(Read("/test/zips"))`, but currently the `ShiftMap` isn’t generated, and the MongoDB backends behaves as if it were.

Adding the `ShiftMap` in the correct place would break the current MongoDB backend, but QScript can effectively patch things up by wrapping any `LP.Read` in a `ShiftMap` during conversion to QScript.

This will make the new backends behave similarly to the MongoDB backend, and once we switch over MongoDB to a QScript-based backend, this fix can be moved to the correct place in the SQL² compiler.

**Comment by jdegoes** [comment]
@sellout Update on this?

**Comment by sellout** [comment]
So, `LP => QScript` currently patches over this, so QScript connectors can do the right thing without having to put work into the old Mongo connector. I think that is the best we can do for 3.1, until the old Mongo connector is removed.

So I’ll update the milestone to 3.2.

**Comment by zeeiyerWork** [comment]
Just ensure that this is fixed - once we switch to "Qscript-based" Mongo connector.

**Comment by sellout** [comment]
@zeeiyerWork This isn’t fixed yet – it’s just not _fixable_ until old Mongo is gone. But it should be a fast change once that happens.

**Comment by alissapajer** [comment]
This would be a good fix to put into the old-mongo-free feature branch when we have that available.

**Comment by alissapajer** [comment]
@sellout is this something that you have already fixed in the new mongo branch? If so, I'll assign this to you.

**Comment by alissapajer** [comment]
@sellout I'm assigning this to you and putting it in June2017 milestone. If this doesn't land at the same time old mongo goes away, feel free to assign back to me.

**Comment by zeeiyerWork** [comment]
Old-mongo is supposed to go away sometime in August -> @alissapajer, based on the commentary,  I have added this in the September Iteration, but accorded it a status of "Fixed in New Mongo" - please lmk if this sounds reasonable. But have added it to the "4.4 target" epic.

**Comment by alissapajer** [comment]
This isn't fixed yet, so it shouldn't have the "Fixed in New Mongo" status. 

@zeeiyerWork moving this tot 4.4 is fine.
